version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.10.2-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - search-engine
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

networks:
  search-engine:
    driver: bridge
    name: search-engine-network
    external: true