server:
  port: 9000
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:
  application:
    name: registration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  search-engine:
    msg:
      notification:
        sender: true

resource:
  secret: ${SECRET_KEY}
  exp:
    access: 60000000
    refresh: 60000000
    confirm: 60000000

email:
  resend: 10
  callback: http://localhost:3000/email/confirm/token/