server:
  port: 8080
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:
  application:
    name: task-manager
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO

resource:
  secret: ${TASK_MANAGER_SECRET}
  types:
    registration:
      name: registration
      baseUrl: http://localhost:9000/api/v1
      secretKey: ${REGISTRATION_SECRET}
      availablePaths:
        registration: /registration
    notification:
      name: notification
      baseUrl: http://localhost:9001/api/v1
      secretKey: ${NOTIFICATION_SECRET}
      availablePaths:
        send: /notification/send
    crawler:
      name: crawler
      baseUrl: http://localhost:8001/api/v1
      secretKey: ${CRAWLER_SECRET}
      availablePaths:
        start: /crawler/start
        stop: /crawler/stop
    indexer:
      name: indexer
      baseUrl: http://localhost:8101/api/v1
      secretKey: ${INDEXER_SECRET}
      availablePaths:
        start: /indexer/start
        stop: /indexer/stop
    searcher:
      name: searcher
      baseUrl: http://localhost:8201/api/v1
      secretKey: ${SEARCHER_SECRET}
      availablePaths:
        start: /searcher/start
        stop: /searcher/stop

