spring:
  application:
    name: logger
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  search-engine:
    common:
      log:
        receiver: true
      metrics:
        receiver: true
