spring:
  application:
    name: logger
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  search-engine:
    msg:
      log:
        sender: false
      task:
        receiver: true
