spring:
  application:
    name: logger
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
  search-engine:
    common:
      log:
        receiver: true
      metrics:
        receiver: true
